UIMARCAUTH-182: Add the Expand the Search & filter pane option
folio-org/ui-marc-authorities pull request #198
Opened 2022-09-08 19:03 UTC by Dmytro-Melnyshyn

## Purpose
See [pull request](https://github.com/folio-org/ui-plugin-find-authority/pull/26)

## Approach

#### TODOS and Open Questions

## Learning

## Screenshots

2022-09-09 13:51 UTC, BogdanDenis approved these changes

2022-09-09 13:54 UTC, BogdanDenis requested changes
Please also remove `onOpenRecord` prop from `SearchResultsList`

2022-09-09 14:39 UTC, Dmytro-Melnyshyn commented
> Please also remove `onOpenRecord` prop from `SearchResultsList`

Thanks for noticing, removed it.

2022-09-12 09:36 UTC, BogdanDenis approved these changes

2022-09-12 14:45 UTC, merged