UIMARCAUTH-369: Add Create a new MARC authority record keyboard shortcut.
folio-org/ui-marc-authorities pull request #359
Opened 2024-01-25 16:17 UTC by Dmytro-Melnyshyn

## Purpose
- MARC authority app - should have the `alt + n` keyboard shortcut for creating a new MARC authority record;
- MARC authority keyboard shortcut modal list - display the new shortcut key as the first row above the Edit a record shortcut key.

## Issues
[UIMARCAUTH-369](https://issues.folio.org/browse/UIMARCAUTH-369)

## Screenshots

![image](https://github.com/folio-org/ui-marc-authorities/assets/77053927/8f54866c-c558-4e91-b5c2-fb143cf130b6)

## Approach

#### TODOS and Open Questions

## Learning

## Screenshots

2024-01-26 11:54 UTC, BogdanDenis approved these changes

2024-01-26 17:36 UTC, zburke requested changes
Functionality looks good, but I have a couple nits in the implementation details. 
* lint is cranky about a `useCallback` dependency array
* consolidating the navigation into a function seems clean but is bad for a11y. Maybe we can stick the URL in a constant referenced by both the button's `to` prop and the function's `history.push()` call?

2024-01-29 15:54 UTC, Dmytro-Melnyshyn commented on src/views/AuthoritiesSearch/AuthoritiesSearch.js
> +              onClick={openCreateAuthorityScreen}
You are right, thank you.

2024-01-31 11:30 UTC, zburke approved these changes

2024-01-31 11:32 UTC, merged