UIMARCAUTH-408 import useUserTenantPermissions from @folio/stripes/core
folio-org/ui-marc-authorities pull request #391
Opened 2024-04-11 04:07 UTC by zburke

Import `useUserTenantPermissions` from `@folio/stripes/core` instead of from `@folio/stripes-authority-components` where it is deprecated.

Must be merged AFTER https://github.com/folio-org/stripes-core/pull/1453.

Refs [UIMARCAUTH-408](https://folio-org.atlassian.net/browse/UIMARCAUTH-408), [STCOR-830](https://folio-org.atlassian.net/browse/STCOR-830)

2024-04-11 08:41 UTC, BogdanDenis requested changes

2024-04-11 08:41 UTC, BogdanDenis commented on CHANGELOG.md
> +- [UIMARCAUTH-408](https://issues.folio.org/browse/UIMARCAUTH-408) Import `useUserTenantPermissions` from `@folio/stripes/core`.
`5.0.1` has been released already. Please create a new section for `5.1.0` release

2024-04-11 13:25 UTC, BogdanDenis approved these changes

2024-04-11 16:44 UTC, zburke commented
Thanks for the review, @BogdanDenis . Do you have any notion of why the AuthoritiesSearch tests are failing? There were no changes to that component. There are lots of complaints about test-actions not wrapped in `act`, but adding it doesn't make a difference. I feel like there must be one small thing wrong with a mock, but I cannot figure what it is.

2024-04-12 15:11 UTC, BogdanDenis commented
Hey @zburke it's because of the Icon mock - it renders additional text to elements and messes up existing selectors.

2024-04-12 17:02 UTC, merged