UIMARCAUTH-29 Browse MARC Authority Records > Results List Sort behavior AND Pagination behavior
folio-org/ui-marc-authorities pull request #75
Opened 2022-02-11 15:16 UTC by BogdanDenis

## Description

## Screenshots

## Issues
[UIMARCAUTH-29](https://issues.folio.org/browse/UIMARCAUTH-29)

2022-02-16 10:55 UTC, mariiaschv requested changes
Impressive job! :clap:
Just some small code style changes needed :)

2022-02-16 10:55 UTC, mariiaschv commented on src/components/AuthoritiesSearchForm/AuthoritiesSearchForm.js
> +  const searchInputRef = useRef();
```suggestion
  });
  
  const searchInputRef = useRef();
```

2022-02-16 10:55 UTC, mariiaschv commented on src/components/SearchFilters/SearchFilters.js
> +import { useCallback, useContext } from 'react';
```suggestion
import {
  useCallback,
  useContext,
} from 'react';
```

2022-02-16 10:55 UTC, mariiaschv commented on src/components/SearchFilters/SearchFilters.test.js
>        const { getByText } = renderSearchFilters();
```suggestion
      mockSetFilters.mockImplementation(setter => setter(defaultCtxValue.filters));
      
      const { getByText } = renderSearchFilters();
```

2022-02-16 10:55 UTC, mariiaschv commented on src/components/SearchFilters/SearchFilters.test.js
> +      const { getByRole } = renderSearchFilters();
```suggestion
      mockSetIsExcludedSeeFromLimiter.mockImplementation(setter => setter(defaultCtxValue.isExcludedSeeFromLimiter));
      
      const { getByRole } = renderSearchFilters();
```

2022-02-16 10:55 UTC, mariiaschv commented on src/context/AuthoritiesSearchContext.js
> +  const locationSearchParams = queryString.parse(location.search);
```suggestion
  const nonFilterUrlParams = ['query', 'qindex', 'segment', 'excludeSeeFrom', 'sort'];
  
  const getInitialFilters = () => {
    return omit(buildFiltersObj(location.search), nonFilterUrlParams);
  };
  
  const locationSearchParams = queryString.parse(location.search);
```

2022-02-16 10:55 UTC, mariiaschv commented on test/jest/helpers/harness.js
> +const AuthotitiesSearchContextProviderMock = ({ children, ctxValue }) => (
Typo here
```suggestion
const AuthoritiesSearchContextProviderMock = ({ children, ctxValue }) => (
```

2022-02-17 09:26 UTC, mariiaschv approved these changes

2022-02-17 09:56 UTC, Svitlana-Korol approved these changes

2022-02-17 12:56 UTC, merged